#!/usr/bin/env python3
"""Generate both _mp3.h and _pcm.h PROGMEM headers from a raw MP3 file.

Usage:
    python3 mp3_file_to_headers.py <input.mp3> <NAME> <out_mp3.h> <out_pcm.h>

Example:
    python3 mp3_file_to_headers.py PhaserMono.mp3 PHASER phaser_mp3.h phaser_pcm.h
"""

import sys
import os
import miniaudio

TARGET_RATE = 44100
TARGET_CHANNELS = 1


def write_mp3_header(out_path, name, mp3_bytes, duration_ms, bitrate_kbps):
    n = len(mp3_bytes)
    with open(out_path, 'w') as f:
        f.write(f'// {name.capitalize()} sound — mono {bitrate_kbps}kbps MP3, ~{duration_ms}ms\n')
        f.write(f'const uint8_t {name}_MP3[] PROGMEM = {{\n')
        for i in range(0, n, 16):
            row = ', '.join(f'0x{b:02X}' for b in mp3_bytes[i:i+16])
            f.write(f'  {row},\n')
        f.write(f'}};\n')
        f.write(f'const size_t {name}_MP3_LEN = {n};\n')


def write_pcm_header(out_path, name, samples, sample_rate):
    n = len(samples)
    duration_ms = int(n * 1000 / sample_rate)
    with open(out_path, 'w') as f:
        f.write(f'// {name} sound — {sample_rate} Hz mono int16 PCM, ~{duration_ms}ms\n')
        f.write(f'// Generated by tools/mp3_file_to_headers.py — do not edit by hand.\n')
        f.write(f'#pragma once\n')
        f.write(f'#include <stdint.h>\n')
        f.write(f'#include <pgmspace.h>\n\n')
        f.write(f'static constexpr int {name}_PCM_RATE   = {sample_rate};\n')
        f.write(f'static constexpr int {name}_PCM_LEN    = {n};\n')
        f.write(f'const int16_t {name}_PCM[] PROGMEM = {{\n')
        for i in range(0, n, 12):
            row = ', '.join(f'{s:6d}' for s in samples[i:i+12])
            f.write(f'  {row},\n')
        f.write(f'}};\n')


def main():
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(1)
    mp3_path, name, mp3_out, pcm_out = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]

    with open(mp3_path, 'rb') as f:
        mp3_bytes = f.read()

    file_size = len(mp3_bytes)

    # Decode to get duration and samples
    decoded = miniaudio.decode_file(
        mp3_path,
        output_format=miniaudio.SampleFormat.SIGNED16,
        nchannels=TARGET_CHANNELS,
        sample_rate=TARGET_RATE,
    )
    samples = list(decoded.samples)
    duration_ms = int(len(samples) * 1000 / TARGET_RATE)
    bitrate_kbps = round((file_size * 8) / duration_ms)

    print(f'MP3: {file_size} bytes, ~{duration_ms}ms, ~{bitrate_kbps}kbps')
    print(f'PCM: {len(samples)} samples at {TARGET_RATE} Hz')

    write_mp3_header(mp3_out, name, mp3_bytes, duration_ms, bitrate_kbps)
    print(f'wrote {mp3_out} ({os.path.getsize(mp3_out)} bytes)')

    write_pcm_header(pcm_out, name, samples, TARGET_RATE)
    print(f'wrote {pcm_out} ({os.path.getsize(pcm_out)} bytes)')


if __name__ == '__main__':
    main()
