#!/usr/bin/env python3
"""Convert an MP3 PROGMEM header (e.g. phaser_mp3.h) to a 22050 Hz mono int16
PCM PROGMEM header. The output is ~16x smaller per second of audio than the
44100 Hz stereo 16-bit alternative and is plenty for short SFX.

Usage:
    python3 mp3_to_pcm_header.py <input_mp3_header.h> <ARRAY_NAME> <output_header.h>

Example:
    python3 mp3_to_pcm_header.py phaser_mp3.h PHASER phaser_pcm.h
"""

import re
import sys
import tempfile
import os
import miniaudio

TARGET_RATE = 44100   # match anthem's native rate so the I2S peripheral is configured once
TARGET_CHANNELS = 1   # mono — MAX98357A is mono, halves flash vs stereo

def extract_bytes(header_text: str) -> bytes:
    # pull out the {... 0xNN, 0xNN ...} initializer
    body = header_text.split('{', 1)[1].rsplit('}', 1)[0]
    return bytes(int(h, 16) for h in re.findall(r'0x[0-9A-Fa-f]+', body))

def decode_mp3(mp3_bytes: bytes) -> miniaudio.DecodedSoundFile:
    with tempfile.NamedTemporaryFile(suffix='.mp3', delete=False) as f:
        f.write(mp3_bytes)
        path = f.name
    try:
        return miniaudio.decode_file(
            path,
            output_format=miniaudio.SampleFormat.SIGNED16,
            nchannels=TARGET_CHANNELS,
            sample_rate=TARGET_RATE,
        )
    finally:
        os.unlink(path)

def write_pcm_header(out_path: str, name: str, samples: list, sample_rate: int):
    n = len(samples)
    duration_ms = int(n * 1000 / sample_rate)
    with open(out_path, 'w') as f:
        f.write(f'// {name} sound — {sample_rate} Hz mono int16 PCM, ~{duration_ms}ms\n')
        f.write(f'// Generated by tools/mp3_to_pcm_header.py — do not edit by hand.\n')
        f.write(f'#pragma once\n')
        f.write(f'#include <stdint.h>\n')
        f.write(f'#include <pgmspace.h>\n\n')
        f.write(f'static constexpr int {name}_PCM_RATE   = {sample_rate};\n')
        f.write(f'static constexpr int {name}_PCM_LEN    = {n};\n')
        f.write(f'const int16_t {name}_PCM[] PROGMEM = {{\n')
        for i in range(0, n, 12):
            row = ', '.join(f'{s:6d}' for s in samples[i:i+12])
            f.write(f'  {row},\n')
        f.write(f'}};\n')

def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    in_path, name, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(in_path) as f:
        header_text = f.read()

    mp3_bytes = extract_bytes(header_text)
    print(f'extracted {len(mp3_bytes)} bytes of MP3 data from {in_path}')

    decoded = decode_mp3(mp3_bytes)
    samples = list(decoded.samples)
    print(f'decoded to {len(samples)} samples at {decoded.sample_rate} Hz '
          f'({decoded.nchannels} ch, {len(samples) * 1000 // decoded.sample_rate} ms)')

    write_pcm_header(out_path, name, samples, decoded.sample_rate)
    print(f'wrote {out_path} ({os.path.getsize(out_path)} bytes)')

if __name__ == '__main__':
    main()
